- name: Build project
  hosts: all

  tasks:
    - name: set run action
      set_fact:
        run_action: build

    - include_role:
        name: build-project
      vars:
        # TODO: pass these vars to the role: 'project_path', 'project_name', 'pkg_name'